server:
  port: 9091

grpc:
  server:
    port: 8091

spring:
  application:
    name: server

  profiles:
    active: dev

  datasource:
    hikari:
      schema: chat
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: default
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
    commit-to-db: commit-to-db


# commented out for docker
#spring.config.import=optional:configserver:http://localhost:8888
