server:
  port: ${PORT:8080}

logging:
  level:
    org:
      atmosphere: warn

spring:
  mustache:
    check-template-location: false

  # PostgreSQL configuration.
#  datasource:
#    url: jdbc:postgresql://localhost:5432/chat
#    username: postgres
#    password: 123
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    defer-datasource-initialization: true

  # Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: true
  # To improve the performance during development.
  # For more information https://vaadin.com/docs/latest/integrations/spring/configuration#special-configuration-parameters
  allowed-packages: com.vaadin,org.vaadin,ru.mai.chat



